### ISSUE TITLE
Open-source schedule and baselins

### ISSUE THREAD

**Issue by Zhen-ao** [zdchan/GraspXL#1]
Hi,

thanks for your sharing, very impressive!

I would like to know your rough open-source time schedule.

**Comment by zdchan** [comment]
Hi,

Thanks for the interest in our work. GraspXL is currently under review and we will release the code as soon as it's accepted, so maybe you can keep an eye on our project page and this repo. 

Best,
Hui

**Comment by zdchan** [comment]
Hi @Zhen-ao,

Our code and dataset have been released. Have fun with it!

Best,
Hui
