### ISSUE TITLE
file "label.pkl" not found when run the test code

### ISSUE THREAD

**Issue by YliangWu** [zdchan/GraspXL#10]
Hi, when i run your test code, it raise "file rsc/**/**label.pkl" not found. 

i check the file "target_label.npy" in each dataset dirs but it still does not match the obj list.

how can i get these .pkl  files?

3Q!  looking forward to your reply!

**Comment by zdchan** [comment]
Hi,

The labels are just pre-sampled objectives used for evaluation, so you can easily sample them by yourself like the demo recording environments. If you want the original labels we used for evaluation, we can also upload them. 

Best,
Hui

**Comment by YliangWu** [comment]
献上感恩的心！

大佬学业顺利！
