### ISSUE TITLE
segmentation fault for the running of raisimUnity.x86_64

### ISSUE THREAD

**Issue by AII6** [zdchan/GraspXL#3]
After I installed raisim according to INSTALLATION.md, I used ./../raisimUnity/linux/raisimUnity.x86_64 to run raisimUnity.x86_64, but it crashed immediately after the window appeared. After adding the -force-opengl suffix, a segmentation error was displayed. The System is Ubuntu20, the nvidia gpu driver version is 560.35.03. Could you help me cope with this error?

**Comment by zdchan** [comment]
Hi this seems a problem from raisim. I have not met such a problem before so I may not able to help with you on this. But maybe you can check the [RaisimUnity](https://raisim.com/sections/RaisimUnity.html) document for help, or creat an issue on their [GitHub repo](https://github.com/raisimTech/raisimlib).

Best,
Hui

**Comment by AII6** [comment]
Thanks, after a series of investigations, it was found that the issue was with Vulkan installation. Reinstalling it successfully resolved the problem.

**Comment by lihaosheng191240022** [comment]
Hi, I am facing the same problem. Could you please tell me how you solved it? @AII6
