### ISSUE TITLE
xx.cpython-38-x86_64-linux-gnu.so

### ISSUE THREAD

**Issue by ZWanG0802** [zdchan/GraspXL#5]
Your work is really impressive! Could you please make the source code of the xx.cpython-38-x86_64-linux-gnu.so file in the raisimGymTorch/raisimGymTorch/env/bin/ directory open source? Thank you so much!

**Comment by zdchan** [comment]
Hi,

These files are just the compiled temporary Python packages compiled from the C++ environments. You need to generate them by yourself every time you change the environments (Environment.hpp in each env).

Best,
Hui
