### ISSUE TITLE
Issues Replacing cube.obj File in URDF Generation Script

### ISSUE THREAD

**Issue by ZWanG0802** [zdchan/GraspXL#7]
Sorry to trouble you again. 

I noticed that cube.obj is directly converted into bottom_watertight_tiny.obj, so I am attempting to replace cube.obj with an obj file that I set as a non-contact area for the fingers. However, when I try to replace cube.obj in the URDF generation script you provided, I encounter an error: **_math.hpp:297 dimension_** mismatch. Do you have any insights on what might be causing this? 

Apologies again for disturbing you during your busy schedule.

![image](https://github.com/user-attachments/assets/531504a1-3915-4230-9924-1f94c8645ba5)

**Comment by zdchan** [comment]
I cannot reproduce your problem on my end. Did you directly replace the .obj file within the urdf folder? Could you replace the cube.obj name in urdf_gen.py to your obj name and rerun the script to generate the urdf?

**Comment by ZWanG0802** [comment]
> I cannot reproduce your problem on my end. Did you directly replace the .obj file within the urdf folder? Could you replace the cube.obj name in urdf_gen.py to your obj name and rerun the script to generate the urdf?

The error occurred while compiling `environment.hpp` using `python setup.py develop --debug`. I also tried modifying the names in the script, but it still had no effect.

**Comment by ZWanG0802** [comment]
Finally, I found the issue: only watertight OBJ files can be input into RaSim.
